### PR TITLE
require

### PR DESCRIPTION
**Pull request by hyperandroid**
add basic `require` support.
 + modules can be cycle-required.
 + understands node_modules and local modules (with and without .js extension).
 + modules can override `exports` object.

### CODE REVIEW

**Comment by modulesio** [comment]
Amazing!

Going forward, is the plan to write the bindings in Swift, or JS? Our [require here seems to be native](https://github.com/webmixedreality/exokit-aura/pull/2/files#diff-531519ce50a591e08389242915fd4eb0R1).

I think the node approach is to mostly implement the root bindings like `fs` in native code and keep higher level concepts in JS. I think it's fine either way; it's just a design decision.

**Comment by hyperandroid** [comment]
since need a way of pulling js modules in JSCore, `require` seems the way to go. And probably one of the few functions Exokit should give for granted. The lack of Nodejs for javascript core bindings forces us to work on a swift binding, switching to just JS whenever possible.

I believe exokit must rely on its own API regardless of how it is implemented per-platform (e.g. much like JavascriprCore, which offers an stable-over-time API, but continually changes all the internal perks of how this public API works).

This means an `exokit.fs` package to access files in a standard way across platforms, but with an specific FS swift binding implementation for iOS. 

What do you think @michaeltheory ?

**Comment by hyperandroid** [comment]
Node's fs is a bit daunting to implement, it is quite big.
The question is more, does exokit need the whole node fs package or just a subset ? 
Why not have an `exokit.fs` package, that relies directly on node's fs package on desktops, but on a smaller fs-like swift binding on iOS ?

So we can keep exokit portable with eventual specific native or js implementations where makes sense ? I am just thinking out loudly.
But to keep things rolling on iOS, we can't simply wait until the whole node's fs package is implemented, while maybe, with just a minimum subset of node's fs package exokit core can just work as expected.

**Comment by michaeltheory** [comment]
Now that we have require, we'll do as many others as possible in JS. 

I'm in agreement, the node stuff such as fs is quite big. I think the best strategy is to get *something* working with a subset and then re-evaluate and go from there.

**Comment by modulesio** [comment]
> The question is more, does exokit need the whole node fs package or just a subset ?

A subset, it's pretty small. It's mostly just file _reading_, and possible directory reading. The main use cases are:

- `require` (handled here)
- `http` `file://` urls for local reading

We also sometimes write for e.g. `localStorage` and config files, but that can be ignored for a basic implementation. Even probably `file://` could be done away with but I think the ability to open a local page shipped with an app is probably important.

**Pull request merged**
